backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Novias"
    name: "novias"
    folder: "content/novias"
    slug: "{{year}}-{{slug}}"
    identifier_field: model
    create: true
    widget: "object"
    summary: "{{fields.name}}: {{fields.birthdate}}"
    fields:
      - label: "Fotos novia"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "novias",
        }
      - { label: "Title", name: "title", widget: "hidden", default: "novias" }
      - { label: "Modelo", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - { label: "Director de arte", name: "artDirector", widget: "string" }
      - { label: "Estilista", name: "stylist", widget: "string" }

  - label: "Moda"
    name: "moda"
    folder: "content/moda"
    slug: "{{year}}-{{slug}}"
    identifier_field: model
    create: true
    widget: "object"
    summary: "{{fields.name}}: {{fields.birthdate}}"
    fields:
      - label: "Fotos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "moda",
        }
      - { label: "Title", name: "title", widget: "hidden", default: "moda" }
      - { label: "Modelo", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - { label: "Director de arte", name: "artDirector", widget: "string" }
      - { label: "Estilista", name: "stylist", widget: "string" }
