backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Novias"
    name: "novias"
    folder: "content/novias"
    slug: "{{year}}-{{slug}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{fields.date}}"
    fields:
      - label: "Fotos novia"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "novias",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Matrimonio", name: "date", widget: "datetime" }
      - { label: "Novia", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - {
          label: "Director de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
      - {
          label: "Estilista",
          name: "stylist",
          widget: "string",
          required: false,
        }

  - label: "Moda"
    name: "moda"
    folder: "content/moda"
    slug: "{{year}}-{{slug}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{fields.date}}"
    fields:
      - label: "Fotos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "moda",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Modelos", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - {
          label: "Director de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
      - {
          label: "Estilista",
          name: "stylist",
          widget: "string",
          required: false,
        }
