backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Novias"
    name: "novias"
    folder: "content/novias"
    slug: "{{fields.title}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Fotos novia"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "novias",
        }
      - { label: "Nombres Pareja", name: "title", widget: "string" }
      - { label: "Fecha Matrimonio", name: "date", widget: "datetime" }
      - {
          label: "Fotografía",
          name: "camera",
          widget: "string",
          required: false,
        }
      - { label: "Peinado", name: "hair", widget: "string", required: false }

  - label: "Moda"
    name: "moda"
    folder: "content/moda"
    slug: "{{fields.title}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Fotos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "moda",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Cliente", name: "client", widget: "string", required: false }
      - {
          label: "Fotografía",
          name: "camera",
          widget: "string",
          required: false,
        }
      - { label: "Model@", name: "model", widget: "string", required: false }
      - { label: "Peinado", name: "hair", widget: "string", required: false }
      - {
          label: "Estilismo",
          name: "stylist",
          widget: "string",
          required: false,
        }
      - {
          label: "Dirección de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }

  - label: "Editorial"
    name: "editorial"
    folder: "content/editorial"
    slug: "{{fields.title}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Fotos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "editorial",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Cliente", name: "client", widget: "string", required: false }
      - {
          label: "Fotografía",
          name: "camera",
          widget: "string",
          required: false,
        }
      - { label: "Model@", name: "model", widget: "string", required: false }
      - { label: "Peinado", name: "hair", widget: "string", required: false }
      - {
          label: "Estilismo",
          name: "stylist",
          widget: "string",
          required: false,
        }
      - {
          label: "Dirección de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }

  - label: "Video"
    name: "video"
    folder: "content/video"
    slug: "{{fields.client}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Videos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Videos, name: video, widget: file }
      - { label: Imagen Portada, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "video",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Cliente", name: "client", widget: "string", required: false }
      - { label: "Video", name: "camera", widget: "string", required: false }
      - { label: "Model@", name: "model", widget: "string", required: false }
      - { label: "Peinado", name: "hair", widget: "string", required: false }
      - {
          label: "Estilismo",
          name: "stylist",
          widget: "string",
          required: false,
        }
      - {
          label: "Dirección de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
