backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Novias"
    name: "novias"
    folder: "content/novias"
    slug: "{{fields.client}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Fotos novia"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "novias",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Matrimonio", name: "date", widget: "datetime" }
      - { label: "Novia", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - {
          label: "Director de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
      - {
          label: "Estilista",
          name: "stylist",
          widget: "string",
          required: false,
        }

  - label: "Moda"
    name: "moda"
    folder: "content/moda"
    slug: "{{fields.client}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Fotos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Image, name: image, widget: image, media_folder: "comercial" }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "moda",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Modelos", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - {
          label: "Director de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
      - {
          label: "Estilista",
          name: "stylist",
          widget: "string",
          required: false,
        }

  - label: "Comercial"
    name: "comercial"
    folder: "content/comercial"
    slug: "{{fields.client}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Fotos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field:
          {
            label: Image,
            name: image,
            widget: image,
            media_folder: "/img/comercial",
          }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "comercial",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Modelos", name: "model", widget: "string" }
      - { label: "Fotógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - {
          label: "Director de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
      - {
          label: "Estilista",
          name: "stylist",
          widget: "string",
          required: false,
        }

  - label: "Video"
    name: "video"
    folder: "content/video"
    slug: "{{fields.client}}-{{slug}}-{{year}}-{{month}}"
    create: true
    widget: "object"
    summary: "{{fields.title}}: {{year}}-{{month}}"
    fields:
      - label: "Videos campaña"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: Videos, name: video, widget: file }
      - { label: Imagen Portada, name: image, widget: image }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "video",
        }
      - { label: "Nombre Campaña", name: "title", widget: "string" }
      - { label: "Fecha Campaña", name: "date", widget: "datetime" }
      - { label: "Modelos", name: "model", widget: "string" }
      - { label: "Camarógrafo", name: "camera", widget: "string" }
      - { label: "Cliente", name: "client", widget: "string" }
      - {
          label: "Director de arte",
          name: "artDirector",
          widget: "string",
          required: false,
        }
      - {
          label: "Estilista",
          name: "stylist",
          widget: "string",
          required: false,
        }
